name: teacher_assistant_app
description: Cross-platform Teacher & Student assistant app with Firebase and Riverpod
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  firebase_messaging: ^14.9.4
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.2.3
  file_picker: ^8.0.3
  video_player: ^2.9.1
  chewie: ^1.7.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true